{
 "title": "Telemetry Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error rate by service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"telemetry\")\r\n  |> filter(fn: (r) => r._field == \"cpu_usage\")\r\n  |> filter(fn: (r) => r.error == \"true\")\r\n  |> drop(columns: [\"region\", \"status_code\", \"error\"])\r\n  |> aggregateWindow(every: 10s, fn: count, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"telemetry\")\r\n  |> filter(fn: (r) => r._field == \"memory_mb\")\r\n  |> drop(columns: [\"region\", \"status_code\", \"error\"])\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"telemetry\")\r\n  |> filter(fn: (r) => r._field == \"latency_ms\")\r\n  |> drop(columns: [\"region\", \"status_code\", \"error\"])\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r._measurement == \"telemetry\")\r\n  |> filter(fn: (r) => r._field == \"cpu_usage\")\r\n  |> drop(columns: [\"region\", \"status_code\", \"error\"])\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}